name: my-phone-shop # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Lab 27 # 79 char long summary
description: |
  Created installer for my phone app on flutter

grade: stable
confinement: strict

apps:
  my-phone-shop:
    command: my_phone_shop
    extensions: [ gnome ]

parts:
  my-phone-shop:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-prime: |
      export PATH="$PWD/flutter/bin:$PATH"